# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  query_log_file: /var/log/prometheus/query.log

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['<prometheus_server_ip>:9090']

  - job_name: 'GPFSAFM_cluster1'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_afm'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSAFMFS_cluster1'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_afmfs'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSAFMFSET_cluster1'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_afmfset'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSFileset_cluster1'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_fileset'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSFilesystem_cluster1'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_filesystem'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSPool_cluster1'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_pool'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSDiskCap_cluster1'
    scrape_interval: 86400s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_diskcap'
    scheme: http
    basic_auth:
      username: 'scale_admin'
      password: 'TXlWZXJ5U3Ryb25nUGFzc3cwcmQhCg=='
    static_configs:
    - targets: ['<cluster1_grafana_bridge_ip>:9250']

  - job_name: 'GPFSDisk_cluster2'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_disk'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']

  - job_name: 'GPFSFileset_cluster2'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_fileset'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']

  - job_name: 'GPFSFilesetQuota_cluster2'
    scrape_interval: 3600s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_filesetquota'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']


  - job_name: 'GPFSFilesystem_cluster2'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_filesystem'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']

  - job_name: 'GPFSPool_cluster2'
    scrape_interval: 300s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_pool'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']

  - job_name: 'GPFSDiskCap_cluster2'
    scrape_interval: 86400s
    honor_timestamps: true
    metrics_path: '/metrics_gpfs_diskcap'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']

  - job_name: 'NFSIO_cluster2'
    scrape_interval: 10s
    honor_timestamps: true
    metrics_path: '/metrics_nfsio'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/cluster2/cert.pem
      key_file: /etc/prometheus/certs/cluster2/privkey.pem
      insecure_skip_verify: true
    basic_auth:
      username: 'scale_admin'
      password_file: /etc/prometheus/certs/cluster2/basic_auth
    static_configs:
    - targets: ['<cluster2_grafana_bridge_ip>:9250']
