apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  namespace: grafana-for-cnsa
  name: grafana-for-cnsa
spec:
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  ingress:
    enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
