# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Software maintenance 🛠 
      labels:
        - "*"
    - title: Features / Enhancements 🎉
      labels:
        - "*"
    - title: Other Changes
      labels:
        - "*"
