---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-bridge
subjects:
  - kind: ServiceAccount
    name: ibm-spectrum-scale-core-operator
roleRef:
  kind: Role
  name: grafana-bridge
  apiGroup: rbac.authorization.k8s.io
