version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    working_directory: ~/ibm-spectrum-scale-bridge-for-grafana
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - python/save-cache
      - run:
          name: Test
          command: |
            . venv/bin/activate
            flake8 --max-line-length=125 --exclude=venv* --statistics
            nosetests tests/


workflows:
  main:
    jobs:
      - build-and-test

