version: 2.1
orbs:
  python: circleci/python@3.0.0
jobs:
  build-and-test:
    executor: python/default
    working_directory: ~/ibm-spectrum-scale-bridge-for-grafana
    steps:
      - checkout
      #- python/load-cache
      - python/install-deps
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      #- python/save-cache
      - run:
          name: Test
          command: |
            . venv/bin/activate
            flake8 --max-line-length=999 --ignore=E731,E741,E712,E722,W503 --exclude=venv* --statistics
            nose2
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            . venv/bin/activate
            docker build -t bridge_image:latest .
workflows:
  main:
    jobs:
      - build-and-test
