---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-bridge-deployment
  serviceAccount: "ibm-spectrum-scale-core-operator"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-bridge
  template:
    metadata:
      labels:
        app: grafana-bridge
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - grafana-bridge
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - scale-pmcollector
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values: [ linux ]
      containers:
        - name: grafana-bridge
          image: <bridge image location/bridge image name:tag>
          env:
          - name: SERVER
            value: $(IBM_SPECTRUM_SCALE_PERF_QUERY_SERVICE_HOST)
          - name: KEYPATH
            value: /opt/registry/certs
          - name: PORT
            value: "8443"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4242
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: logfiles
              mountPath: /opt/IBM/bridge/logs
            - name: config
              mountPath: /opt/IBM/zimon/
              readOnly: true
              optional: true
            - name: secret-volume
              mountPath: /opt/registry/certs
      initContainers:
      - name: init-scale-perf-query-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup ibm-spectrum-scale-perf-query.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for ibm-spectrum-scale-perf-query service; sleep 2; done"]
      imagePullSecrets:
        - name: spectrumscale-registrykey
      volumes:
        - name: logfiles
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: grafana-bridge-secret
        - name: config
          projected:
            sources:
            - configMap:
                name: ibm-spectrum-scale-pmsensors-config
                items:
                  - key: "ZIMonSensors.cfg"
                    path: "ZIMonSensors.cfg"
            - configMap:
                name: ibm-spectrum-scale-pmcollector
                items:
                  - key: "ZIMonCollector.cfg"
                    path: "ZIMonCollector.cfg"
