---
apiVersion: v1
kind: Service
metadata:
  name: grafana-bridge
  namespace: <namespace-name of the CNSS project>
  labels:
    app: grafana-bridge
spec:
  ports:
    - port: 4242
      name: http
    - port: 8443
      name: https
  selector:
    app: grafana-bridge
